"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import store from "../../store/store";
import { Provider } from "react-redux";
import Menubar from "../../components/Menubar";

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Menubar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
